// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	kinesis "github.com/aws/aws-sdk-go/service/kinesis"
	mock "github.com/stretchr/testify/mock"
)

// FileKinesis is an autogenerated mock type for the FileKinesis type
type FileKinesis struct {
	mock.Mock
}

// PutRecord provides a mock function with given fields: _a0
func (_m *FileKinesis) PutRecord(_a0 *kinesis.PutRecordInput) (*kinesis.PutRecordOutput, error) {
	ret := _m.Called(_a0)

	var r0 *kinesis.PutRecordOutput
	if rf, ok := ret.Get(0).(func(*kinesis.PutRecordInput) *kinesis.PutRecordOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.PutRecordOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*kinesis.PutRecordInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
