// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Log provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *Logger) Log(_a0 echo.Context, _a1 string, _a2 string, _a3 error, _a4 map[string]interface{}) {
	_m.Called(_a0, _a1, _a2, _a3, _a4)
}
