// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	gox "github.com/konstantinfarrell/go-example"
	file "github.com/konstantinfarrell/go-example/pkg/api/file"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *Service) Create(_a0 chan gox.FileChannel, _a1 file.Context, _a2 *gox.File) {
	_m.Called(_a0, _a1, _a2)
}

// Delete provides a mock function with given fields: _a0, _a1, _a2
func (_m *Service) Delete(_a0 chan gox.FileChannel, _a1 file.Context, _a2 *gox.File) {
	_m.Called(_a0, _a1, _a2)
}

// Read provides a mock function with given fields: _a0, _a1, _a2
func (_m *Service) Read(_a0 chan gox.FileChannel, _a1 file.Context, _a2 *gox.File) {
	_m.Called(_a0, _a1, _a2)
}

// ReadAll provides a mock function with given fields: _a0, _a1
func (_m *Service) ReadAll(_a0 chan gox.FileChannel, _a1 file.Context) {
	_m.Called(_a0, _a1)
}
